In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [3]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [4]:
arr = np.arange(2,26)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25])

In [5]:
arr.reshape(4,6)

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25]])

In [6]:
arr[3]

5

In [7]:
arr_2d = np.array([[2,45,3],[65,4,8],[8,9,2]])

In [8]:
arr_2d

array([[ 2, 45,  3],
       [65,  4,  8],
       [ 8,  9,  2]])

In [9]:
arr_2d[1][:2]

array([65,  4])

In [10]:
bool_arr = arr > 5

In [12]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25])

In [13]:
arr[arr<7]

array([2, 3, 4, 5, 6])

In [14]:
ar2d = np.arange(50).reshape(5,10)

In [15]:
ar2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [19]:
ar2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [22]:
ar2d[:1,]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### NumPy Operatons

In [23]:
ar2d/0

/var/folders/jr/gmkpvjsn5bg6fn2p7nsnqwb00000gn/T/ipykernel_4505/989016373.py:1: RuntimeWarning: divide by zero encountered in true_divide
  ar2d/0
/var/folders/jr/gmkpvjsn5bg6fn2p7nsnqwb00000gn/T/ipykernel_4505/989016373.py:1: RuntimeWarning: invalid value encountered in true_divide
  ar2d/0


array([[nan, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf]])